### ISSUE TITLE
OSX: High Sierra Fork Support

### ISSUE THREAD

**Issue by MutableLoss** [paraspec/paraspec#16]
**Issue**: Paraspec will give the following error on startup with OSX 10.13.6

```
objc[4733]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[4733]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

/Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/msgpack_client.rb:47:in `sleep': Interrupt
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/msgpack_client.rb:47:in `rescue in connect'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/msgpack_client.rb:41:in `connect'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/msgpack_client.rb:11:in `initialize'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/drb_helpers.rb:61:in `new'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/drb_helpers.rb:61:in `master_client'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/supervisor.rb:67:in `run_supervisor'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/lib/paraspec/supervisor.rb:49:in `run'
        from /Users/dbrown/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paraspec-0.0.2/bin/paraspec:53:in `<top (required)>'
        from /Users/dbrown/.rbenv/versions/2.4.1/bin/paraspec:22:in `load'
        from /Users/dbrown/.rbenv/versions/2.4.1/bin/paraspec:22:in `<main>'
```

I tried 5 different projects, 3 being rails apps, and I can only get this to happen when paraspec is loading a rails_helper file prior to testing. Testing outside of Rails works perfectly.

I was able to narrow this down, and it happens when loading the environment file form the spec file. I was able to reproduce by creating an empty rails_helper that only imported the rails environment file.

```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
```

**Workaround**

This has been an issue for many Ruby and Python gems that fork processes, and the proposed workaround is to use ```export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES```.

**Additional Information**: 

Documentation on the issue:

http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html

Ruby Trunk issue:

https://bugs.ruby-lang.org/issues/14009

**Comment by p-mongo** [comment]
Thanks for the report, what do you mean by "loading prior to testing" though? Paraspec is meant to start in a pristine environment with none of the application loaded in the supervisor.

**Comment by 3DEsprit** [comment]
Sorry for the confusion, and great to know! 

Rephrase: Prior to the tests being run in the process itself, during the stage of the rails_helper being processed.

**Comment by p-mongo** [comment]
OK, can you then set `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` in your environment for all projects? Any reason not to do that?

**Comment by p-mongo** [comment]
I made an effort to minimize open network connections during forks but perhaps this can be improved further. Is the stack trace posted accurate with respect to where the issue surfaces?

**Comment by 3DEsprit** [comment]
Absolutely. 

One detail I did forget to mention is that the trace itself is from a manual break, since the process will actually sleep after these errors. Even so, the trace given is consistent across multiple attempts.

Watching the activity after execution I can see it creates the subprocess, subprocess dies, and main process goes to sleep.

**Comment by p-mongo** [comment]
paraspec hanging is a bug in any event, that shouldn't be happening.
