### ISSUE TITLE
Paraspec::InconsistentTestSuite

### ISSUE THREAD

**Issue by Nerian** [paraspec/paraspec#32]
Hi,

I am getting this error, a Paraspec::InconsistentTestSuite exception. I am not sure what steps can I take to resolve it. Any advise would be appreciated.

Thanks

```
bin/paraspec -c 2 -d state -- spec/controllers

3820 example groups queued

D, [2021-04-22T18:36:53.755791 #22770] DEBUG -- : [s] [state] Waiting for workers
D, [2021-04-22T18:36:53.756053 #22770] DEBUG -- : [s] [state] Waiting for worker 1 at 22781
Worker 2 has 2838 examples, master has 0
dumping summary
Worker 1 has 2838 examples, master has 0
dumping summary

Finished in 14.82 seconds (files took 0 seconds to load)
0 examples, 0 failures

Finished in 14.82 seconds (files took 0 seconds to load)
0 examples, 0 failures

Traceback (most recent call last):
	10: from bin/paraspec:29:in `<main>'
	 9: from bin/paraspec:29:in `load'
	 8: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/bin/paraspec:63:in `<top (required)>'
	 7: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:70:in `run'
	 6: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:115:in `run_supervisor'
	 5: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:153:in `start_workers'
	 4: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:153:in `upto'
	 3: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:154:in `block in start_workers'
	 2: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:171:in `spawn_worker'
	 1: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:185:in `run_worker'
/Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/worker.rb:50:in `run': Worker 2 has 2838 examples, master has 0 (Paraspec::InconsistentTestSuite)

Traceback (most recent call last):
	10: from bin/paraspec:29:in `<main>'
	 9: from bin/paraspec:29:in `load'
	 8: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/bin/paraspec:63:in `<top (required)>'
	 7: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:70:in `run'
	 6: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:115:in `run_supervisor'
	 5: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:153:in `start_workers'
	 4: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:153:in `upto'
	 3: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:154:in `block in start_workers'
	 2: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:171:in `spawn_worker'
	 1: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:185:in `run_worker'
/Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/worker.rb:50:in `run': Worker 1 has 2838 examples, master has 0 (Paraspec::InconsistentTestSuite)
dumping summary

Finished in 16.64 seconds (files took 0 seconds to load)
0 examples, 0 failures
Traceback (most recent call last):
	9: from bin/paraspec:29:in `<main>'
	8: from bin/paraspec:29:in `load'
	7: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/bin/paraspec:63:in `<top (required)>'
	6: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:70:in `run'
	5: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:116:in `run_supervisor'
	4: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:190:in `wait_for_workers'
	3: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:190:in `each_with_index'
	2: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:190:in `each'
	1: from /Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:192:in `block in wait_for_workers'
/Users/Nerian/.rvm/gems/ruby-2.6.5/bundler/gems/paraspec-1ccc2e9192c3/lib/paraspec/supervisor.rb:210:in `wait_for_process': Worker 1 exited with status 1 (Paraspec::WorkerFailed)
```

**Comment by p** [comment]
Your master didn't get any tests loaded in it. To troubleshoot, try to reduce your test suite until the error goes away.

**Comment by Nerian** [comment]
Thanks. Closing this as no longer relevant.
